# Generated by Django 3.1.4 on 2020-12-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, default='1024.jpg', null=True, upload_to='User_images/'),
        ),
    ]
